{% set name = "semantikon" %}
{% set version = "0.0.26" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b76b0f12a4bfb50bab44060b9c493ccac6da72540f77d9fa7507bd202922b590

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >={{ python_min }},<3.15
    - python-graphviz >=0.20.3,<=0.21
    - networkx >=3.4.2,<3.5.0
    - numpy >=1.26.3,<2.4.0
    - owlrl >=7.1.2,<7.2.0
    - pint >=0.23,<=0.25.2
    - rdflib >=7.1.1,<7.5.0
    - pyshacl >=0.30.0,<=0.30.1
    - requests >=2.28.0,<2.33.0
    - typeguard >=4.0.0,<4.5.0

test:
  imports:
    - semantikon
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/pyiron/semantikon
  summary: 'semantikon - Ontological type system'
  description: |
    In the realm of the workflow management systems, there are well defined inputs and outputs for each node. semantikon is a Python package to give scientific context to node inputs and outputs by providing type hinting and interpreters.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://semantikon.readthedocs.io/
  dev_url: https://github.com/pyiron/semantikon

extra:
  recipe-maintainers:
    - jan-janssen
    - samwaseda
    - liamhuber
