{% set name = "semantikon" %}
{% set version = "0.0.17" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c46849be2679c1834357e18d79880b92c475dc624af4013a4352bc9b2982d175

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - versioneer
  run:
    - python >={{ python_min }},<3.13
    - networkx >=3.4.2, <=3.4.2
    - numpy >=1.26.3, <=2.2.3
    - owlrl >=7.1.2, <=7.1.2
    - pint >=0.24.3, <=0.24.4
    - rdflib >=7.1.1, <=7.1.1
    - pyshacl >=0.30.0, <=0.30.1

test:
  imports:
    - semantikon
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/pyiron/semantikon
  summary: 'semantikon - Ontological type system'
  description: |
    In the realm of the workflow management systems, there are well defined inputs and outputs for each node. semantikon is a Python package to give scientific context to node inputs and outputs by providing type hinting and interpreters.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://semantikon.readthedocs.io/
  dev_url: https://github.com/pyiron/semantikon

extra:
  recipe-maintainers:
    - samwaseda
    - liamhuber
